services:
  odc:
    build:
      context: ..
      dockerfile: build/Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    environment:
      # ODC container ID (Hash). If not provided, validation is skipped
      - ODC_ID=b47db6afe3254cf4a3797603227d0e7b993fcd20584ffec7d2cc5545066a2407
      # If specified, only allow that UDC ID. Otherwise, allow all
      - UDC_ID=50c07323d778f35f471941d0e435cf67e1ca2d2dda4156961d6510015a556c9d
      - OTP_SEED=
      - UDC_SERVER=http://udc:8080
      # Model execution script. Script is separated to set custom parameters and environment variables. Default: /model/script.sh
      - MODEL_SCRIPT=
      # Model execution result file name
      - MODEL_OUTPUT_FILE_NAME=
    volumes:
      # require
      - /var/run/docker.sock:/var/run/docker.sock
      # Must specify the paths to the actual model script file
      - ./script.sh:/model/script.sh
      # Container execution result. Returns error if file is missing or result is not success
      # Fixed internal path: /tmp/odc/result.txt
      - ./result/:/tmp/odc/

    networks:
      - shared-network

networks:
  shared-network:
    # Use externally created network
    external: true