services:
  udc:
    build:
      context: ..
      dockerfile: build/Dockerfile
    privileged: true
    ports:
      - "8080:8080"         # UDC Server Port (configurable)
      - "111:111/tcp"       # RPC Portmapper
      - "111:111/udp"       # RPC Portmapper
      - "2049:2049/tcp"     # NFS
      - "2049:2049/udp"     # NFS
      - "20048:20048/tcp"   # Mountd
      - "20048:20048/udp"   # Mountd
    environment:
      # recommend using UDC container hash
      - UDC_ID=50c07323d778f35f471941d0e435cf67e1ca2d2dda4156961d6510015a556c9d
      # ODC container ID (Hash). If not provided, validation is skipped
      - ODC_ID=b47db6afe3254cf4a3797603227d0e7b993fcd20584ffec7d2cc5545066a2407
      # If specified, only allow that IP. Otherwise, allow all IPs
      - ODC_IP=
      # UDC HOST information. If empty, it will be set to the public IP.
      - UDC_HOST=udc
      # Model path is relative to container. Default: /model/model.tar
      - MODEL_PATH=
      # Model execution script. Script is separated to set custom parameters and environment variables. Default: /model/script.sh
      - MODEL_SCRIPT=
    volumes:
      # require
      - /var/run/docker.sock:/var/run/docker.sock
      # Docker's default filesystems (overlay2, aufs, etc.) do not support NFS export, so host mount is required
      - ./nfs:/nfs/share
      # Must specify the paths to the actual model and script files
      - ./:/model/
      # ODC model execution result file. Error if file doesn't exist or is empty
      # Fixed internal dir: /tmp/result/
      - ./result:/tmp/result/
    # nfs file clear.
    stop_signal: SIGTERM
    stop_grace_period: 3s
    networks:
      - shared-network
networks:
  shared-network:
    driver: bridge
    name: shared-network
    external: true